services:
  app:
    image: ${DOCKER_REPOSITORY_TICKETING}:${IMAGE_TAG_TICKETING}
    container_name: ticketing
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      JAVA_TOOL_OPTIONS: >-
        -Xms1024m
        -Xmx1024m
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/dump
    volumes:
      - ./logs:/app/logs  # alloy가 읽을 수 있도록 마운트
      - ./dump:/dump
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    environment:
      - ALLOY_ENV=prod  # alloy config 에서 운영 환경을 라벨로 구분하기 위함
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./logs:/var/log/spring:ro  # app 이 남긴 파일 로그를 읽는다
    restart: unless-stopped

  node-exporter:
    depends_on:
      - app
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: host           # 컨테이너가 아닌 호스트 레벨 프로세스를 보도록
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
