spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/ticketing
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: master-pool
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/ticketing
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: slave-pool
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false   # @Transactional 안에서 연관관계 로딩 및 DTO를 반환하므로, 컨트롤러 레이어까지 가지 않음
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret: large-ticketing-jwt-secret-key-local-dev-only-please-change
    expiration: 1800000

# 인스턴스 역할. API 서버인지, 대기열 서버인지
app:
  role: ${APP_ROLE:all}
  scheduler:
    enabled: ${SCHEDULER_ENABLED:true}
