services:
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro # bind (설정파일은 ro)
      - ./prometheus/rules:/etc/prometheus/rules:ro # 알람 규칙 (설정파일은 ro)
      # - ./monitoring/data/prometheus:/prometheus # prometheus가 메트릭 저장 경로 TSDB (나중에 과거 메트릭도 확인하려면 주석 해제. 여기서는 필요 X)
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"  # config 파일 경로
      - "--storage.tsdb.path=/prometheus"               # TSDB 데이터 저장 경로
      - "--storage.tsdb.retention.time=15d"             # 수집 메트릭의 보존 기간 (디폴트가 15days)
      - "--storage.tsdb.wal-compression"                # WAL 압축 (디스크 절약, CPU 약간 증가)
      - "--web.enable-remote-write-receiver"            # 외부에서 메트릭 주입 허용 for k6
      - "--web.enable-lifecycle"                        # Reload API를 통한 무중단 리로드 활성화
    networks:
      - monitoring
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning # bind
      - grafana-data:/var/lib/grafana # volume (대시보드 설정, 소스, 계정 ...)
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
