server:
  tomcat:
    mbeanregistry:
      enabled: true  # Tomcat Threads metric 활성화
    threads:
      max: 200
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 2048

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://${DB_MASTER_URL}?rewriteBatchedStatements=true&useServerPrepStmts=false
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: master-pool
      maximum-pool-size: 3  # LB 인스턴스 수 고려
    slave:
      jdbc-url: jdbc:mysql://${DB_SLAVE_URL}?rewriteBatchedStatements=true&useServerPrepStmts=false
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: slave-pool
      maximum-pool-size: 5  # LB 인스턴스 수 고려
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false   # @Transactional 안에서 연관관계 로딩 및 DTO를 반환하므로, 컨트롤러 레이어까지 가지 않음
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1800000

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, info, env, loggers
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted # unrestricted: 인증 없이 전체 접근 허용 / read-only: 읽기만 허용 / none: 비활성화
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ticketing  # Grafana에서 앱 식별용 (대기열 서버는 queue)
      namespace: ticketing    # namespace