server:
  tomcat:
    mbeanregistry:
      enabled: true  # Tomcat Threads metric 활성화
    threads:
      max: 200
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 2048

# 대기열 서버는 DB에 접속하지 않으므로 datasource/jpa 설정을 두지 않는다
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1800000

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, info, env, loggers
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted # unrestricted: 인증 없이 전체 접근 허용 / read-only: 읽기만 허용 / none: 비활성화
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: queue      # Grafana에서 앱 식별용 (티켓팅 서버는 ticketing)
      namespace: ticketing    # namespace
  threads:
    virtual:
      enabled: true